

name: My first workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fist-job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: echo "Hello, welcome to first action"
      - name: Print goodby
        name: echo "Googbye, hope you enjoyed it!"
    
